language: php

services:
    - docker

php:
    - 7.2
    - 7.3
    - 7.4
    - 7.4snapshot
    - nightly

matrix:
    allow_failures:
        - php: 7.4snapshot
        - php: nightly

sudo: false

install:
    - travis_retry composer install

script:
    - vendor/bin/phpunit --coverage-text
